services:
  - type: web
    name: smep-portal
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://mohitkr7982_db_user:FFTvdQYPH1DaOsVq@cluster0.oeprtwt.mongodb.net/smep_db?retryWrites=true&w=majority
